#!/bin/sh
#
# Minimal installation steps for Archlinux.
# Few prompts. Lots of assumptions. Only tested on virtual machines.
#

set -ue

# Set keyboard layout.
ls /usr/share/kbd/keymaps/**/*.map.gz
echo "Pick a keyboard layout: (e.g. br-abnt2)"
read -p ">" layout
loadkeys $layout

# Check internet connection.
ip link
ping -c5 archlinux.org || { echo "Something's up with your connection." >&2; exit 1; }

# Sync time.
timedatectl set-ntp true

# Prepare disk.
lsblk
echo "What disk will be used to install Archlinux? (e.g. /dev/sda)" 
read -p ">" disk
fdisk $disk

# Ask for install partition and format it.
echo "What partition will be used to install Archlinux? (e.g. /dev/sda2)"
read -p ">" root
mkfs.ext4 $root

# Enlist closest mirror. 
# TODO: add extra mirrors.
cat <<-EOF > /etc/pacman.d/mirrorlist
	Server = http://br.mirror.archlinux-br.org/\$repo/os/\$arch
	Server = http://archlinux.c3sl.ufpr.br/\$repo/os/\$arch
	Server = http://www.caco.ic.unicamp.br/archlinux/\$repo/os/\$arch
	Server = https://www.caco.ic.unicamp.br/archlinux/\$repo/os/\$arch
	Server = http://linorg.usp.br/archlinux/\$repo/os/\$arch
	Server = http://pet.inf.ufsc.br/mirrors/archlinux/\$repo/os/\$arch
	Server = http://archlinux.pop-es.rnp.br/\$repo/os/\$arch
	Server = http://mirror.ufam.edu.br/archlinux/\$repo/os/\$arch
	Server = http://mirror.ufscar.br/archlinux/\$repo/os/\$arch
EOF

# Enable multilib repository for 32bit applications.
#sed -zi "s/#\[multilib\]\n#/[multilib]\n/" /etc/pacman.conf

# Just do it! (install the system)
mount $root /mnt
pacstrap /mnt base base-devel

# Generate fstab and confirm.
genfstab -U -p /mnt >> /mnt/etc/fstab
nano /mnt/etc/fstab

# Change root.
arch-chroot /mnt

# Setup GRUB.
pacman -S grub 
if test -d /sys/firmware/efi; then
	echo "What partition will used to setup EFI? (e.g. /dev/sda1)"
	read -p ">" efi
	mkfs.fat -F32 $efi
	pacman -S efibootmgr
	mkdir /boot/EFI
	mount $efi /boot/EFI
	grub-install --target=x86_64-efi --bootloader-id=GRUB --recheck
else
	echo "What disk will be used to install GRUB? (e.g. /dev/sda)"
	read -p ">" grub
	grub-install --target=i386-pc $grub
fi
grub-mkconfig -o /boot/grub/grub.cfg

# Set hostname and locale.
echo "archlinux" > /etc/hostname
cat <<-EOF > /etc/locale.gen
	en_US.UTF-8 UTF-8
	en_US ISO-8859-1
EOF
locale-gen
export LANG=en_US.UTF-8
echo "LANG=$LANG" > /etc/locale.conf

# Pick a timezone.
ls /usr/share/zoneinfo/
echo "What timezone you're in? (e.g. Brazil/East)"
read -p ">" timezone
ln -sf /usr/share/zoneinfo/$timezone /etc/localtime

# Set hardware clock.
hwclock --systohc --utc

# Persist keyboard layout.
cat <<-EOF > /etc/vconsole.conf
    KEYMAP=$layout
EOF

# Setup accounts.
echo "Enter your username: (e.g. arthur)"
read -p ">" username
useradd -mg users -G wheel,storage,power -s /bin/bash $username
passwd $username

# Setup sudo and confirm.
pacman -S sudo
EDITOR=nano visudo

# Setup AUR.
pacman -S git
git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin
cd /tmp/yay-bin
makepkg -sri

# Setup X and i3.
#pacman -S xorg xorg-xinit xrvt-unicode uxrvt-perls i3 i3blocks i3lock
#cat <<-EOF >> /etc/profile
#	test "$(tty)" = "/dev/tty1" && startx
#EOF

# Done.
exit
umount -a
echo -e "Done! Type 'telinit 6' to reboot.\n"

# Troubleshooting:
#
# 1. Authentication token manipulation error trying to login?
# A: Use root or live boot to change password and try again.
#
# 2. No internet connection?
# A: Check device status and name with `ip addr` then run `sudo dhcpd en0` where `en0` is the name of your link.
#