#!/usr/bin/env bash
#
# Minimal installation steps for Archlinux.
# Few prompts. Lots of assumptions. Only tested on virtual machines.
#

set -ueo pipefail

keyboard_layout=br-abnt2
timezone=Brazil/East
disk=/dev/sda
os_partition=/dev/sda2
efi_partition=/dev/sda1
net_interface=enp0s3
username=arthur
chrooted=

while test $# -gt 0; do
	case "$1" in 
		-k|--keyboard-layout)
			keyboard_layout="$2"
			shift
			;;
		-d|--disk)
			disk="$2"
			shift
			;;
		-p|--os-partition)
			os_partition="$2"
			shift
			;;
		-e|--efi-partition)
			efi_partition="$2"
			shift
			;;
		-n|--net-interface)
			net_interface="$2"
			shift
			;;
		-u|--username)
			username="$2"
			shift
			;;
		-t|--timezone)
			timezone="$2"
			shift
			;;
		-r|--chrooted)
			chrooted="chrooted"
			;;
	esac
	shift
done

printf "

The script will use the following configuration:

 - Keyboard layout:   [-k] $keyboard_layout 
 - Timezone:          [-t] $timezone
 - Disk:              [-d] $disk
 - OS partition:      [-p] $os_partition
 - EFI partition:     [-e] $efi_partition
 - Network interface: [-n] $net_interface
 - Username:          [-u] $username

Press ENTER to continue or CTRL-C to abort...
"
read -rs _

if test -n "$chrooted"; then
	# Update everything.
	pacman -Syyu

	# Ask DHCP on boot.
	systemctl enable dhcpcd@$net_interface.service

	# Setup GRUB.
	pacman -S grub 
	if test -d /sys/firmware/efi; then
		mkfs.fat -F32 $efi_partition
		pacman -S efibootmgr
		mkdir /boot/EFI
		mount $efi_partition /boot/EFI
		grub-install --target=x86_64-efi --bootloader-id=GRUB --recheck
	else
		grub-install --target=i386-pc $disk
	fi
	grub-mkconfig -o /boot/grub/grub.cfg

	# Set hostname and locale.
	echo "archlinux" > /etc/hostname
	cat <<-EOF > /etc/locale.gen
		en_US.UTF-8 UTF-8
		en_US ISO-8859-1
	EOF
	locale-gen
	export LANG=en_US.UTF-8
	echo "LANG=$LANG" > /etc/locale.conf

	# Pick a timezone.
	ls /usr/share/zoneinfo/
	ln -sf /usr/share/zoneinfo/$timezone /etc/localtime

	# Set hardware clock.
	hwclock --systohc --utc

	# Persist keyboard layout.
	cat <<-EOF > /etc/vconsole.conf
		KEYMAP=$layout
	EOF

	# Setup accounts.
	useradd -mg users -G wheel,storage,power -s /bin/bash $username
	passwd $username

	# Setup sudo and confirm.
	pacman -S sudoe
	EDITOR=nano visudo

	# Setup X and i3.
	pacman -S xorg xorg-xinit xrvt-unicode uxrvt-perls i3
	cat <<-EOF >> /etc/profile
		test "$(tty)" = "/dev/tty1" && startx
	EOF

	# Done.
	exit
fi

# Set keyboard layout.
ls /usr/share/kbd/keymaps/**/*.map.gz
loadkeys $keyboard_layout

# Check internet connection.
ping -c3 archlinux.org || { echo "Something's up with your connection." >&2; exit 1; }

# Sync time.
timedatectl set-ntp true

# Prepare disk.
fdisk $disk

# Ask for install partition and format it.
mkfs.ext4 $os_partition

# Enlist closest mirror. 
# TODO: add extra mirrors.
cat <<-EOF > /etc/pacman.d/mirrorlist
	Server = http://br.mirror.archlinux-br.org/\$repo/os/\$arch
	Server = http://archlinux.c3sl.ufpr.br/\$repo/os/\$arch
	Server = http://www.caco.ic.unicamp.br/archlinux/\$repo/os/\$arch
	Server = https://www.caco.ic.unicamp.br/archlinux/\$repo/os/\$arch
	Server = http://linorg.usp.br/archlinux/\$repo/os/\$arch
	Server = http://pet.inf.ufsc.br/mirrors/archlinux/\$repo/os/\$arch
	Server = http://archlinux.pop-es.rnp.br/\$repo/os/\$arch
	Server = http://mirror.ufam.edu.br/archlinux/\$repo/os/\$arch
	Server = http://mirror.ufscar.br/archlinux/\$repo/os/\$arch
EOF

# Enable multilib repository for 32bit applications.
#sed -zi "s/#\[multilib\]\n#/[multilib]\n/" /etc/pacman.conf

# Just do it! (install the system)
mount $os_partition /mnt
pacstrap /mnt base base-devel

# Generate fstab and confirm.
genfstab -U -p /mnt >> /mnt/etc/fstab
nano /mnt/etc/fstab

# Change root.
cp $0 /mnt/root/
arch-chroot /mnt /root/$(basename $0) --chrooted

# Done
umount -a
echo -e "Done! Type 'telinit 6' to reboot.\n"
